export const SEARCH_STOCK = 'stock'
export const SEARCH_INDUSTRY = 'industry_search'
export const SEARCH_MUTUAL_FUND = 'industry_search'
export const BSE_MOST_ACTIVE = 'BSE_most_active'
export const NSE_MOST_ACTIVE = 'NSE_most_active'
export const FETCH_52_WEEK_HIGH_LOW = 'fetch_52_week_high_low_data'
export const TRENDING_STOCKS = 'trending'
