#!/usr/bin/env sh

# Disable the hooks in CI 
[ -n "$CI" ] && exit 0

# Formats staged code using prettier
# Checks and fixes all lint issues in code which don't require manual intervention.
# Throws errors if lint issues requiring manual intervention are found in code.
npm run lint-staged

# Add the changes made to the stage
git add .